# location of struct and traj files for each simulation

simulations:
  sim_1:
    structure_file: "../gromacs/sim_1/confout_10210.gro"
    trajectory_file: "../gromacs/sim_1/traj_comp.xtc"
  sim_2:
    structure_file: "../gromacs/sim_2/confout_10510.gro"
    trajectory_file: "../gromacs/sim_2/traj_comp.xtc"
  sim_3:
    structure_file: "../gromacs/sim_4/confout_10810.gro"
    trajectory_file: "../gromacs/sim_3/traj_comp.xtc"
  sim_4:
    structure_file: "../gromacs/sim_4/congout_10.gro"
    trajectory_file: "../gromacs/sim_4/traj_comp.xtc"